services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/home
    working_dir: /home
    command: npm start
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    command: php artisan serve --host=0.0.0.0 --port=8001
    ports:
      - "8001:8001"
    depends_on:
      - database
      
  database:
    image: mysql:8.0
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
        - "3306:3306"